# Generated by Django 4.2.7 on 2023-11-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100)),
                ('calling_number', models.CharField(max_length=20)),
                ('called_number', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('call_status', models.CharField(choices=[('SUCCESS', 'Успешный'), ('UNANSWERED', 'Неотвеченный'), ('REJECTED', 'Отклоненный')], max_length=50)),
                ('call_type', models.CharField(choices=[('OUTGOING', 'Исходящий'), ('INCOMING', 'Входящий'), ('MISSED', 'Пропущенный')], max_length=50)),
            ],
        ),
    ]
